Domaci_MVC_1/Models/Bookstore.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Domaci_MVC_1.Models
{
    public class Bookstore
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Book> Books { get; set; }
    }
}

Domaci_MVC_1/Controllers/BookstoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domaci_MVC_1.Models;
using Domaci_MVC_1.ViewModels;
using Domaci_MVC_1.Repository;

namespace Domaci_MVC_1.Controllers
{
    [RoutePrefix("knjige")]
    public class BookstoreController : Controller
    {

        //public static List<Book> listaKnjiga  = new List<Book>();
        //public static List<Genre> listaZanrova = new List<Genre>();
        private static IRepository<Genre> genreRepo = new GenreRepository();
        private static IRepository<Book> bookRepo = new BookRepository();

        #region nekoriscen metod
        //public static void PopuniListuKnjiga()
        //{
        //         Book book1 = new Book("Harry Potter", 200, BookGenre.Science, false);
        //        Book book2 = new Book("Game of Thrones", 222, BookGenre.Comedy, false);

        //        book1.AddChapter("Chapter 1", "Ovo je sadržaj Chapter 1, prve knjige");
        //        book1.AddChapter("Chapter 2", "Ovo je sadržaj Chapter 2, prve knjige");

        //        book2.AddChapter("Chapter 1", "Ovo je sadržaj Chapter 1, druge knjige");
        //        book2.AddChapter("Chapter 2", "Ovo je sadržaj Chapter 2, druge knjige");

        //        listaKnjiga.Add(book1);
        //        listaKnjiga.Add(book2);

        //}
        #endregion
            
        static BookstoreController()
        {
            #region hardocoded liste
            //PopuniListuKnjiga();
            //Genre genre1 = new Genre("Science");
            //Genre genre2 = new Genre("Comedy");
            //Genre genre3 = new Genre("Horror");

            //Book book1 = new Book("Harry Potter", 200, genre1, false);
            //Book book2 = new Book("Game of Thrones", 222, genre2, false);
            //Book book3 = new Book("Lord of the Rings", 300, genre3, false);

            //book1.AddChapter("Chapter 1", "Ovo je sadržaj Chapter 1, prve knjige");
            //book1.AddChapter("Chapter 2", "Ovo je sadržaj Chapter 2, prve knjige");

            //book2.AddChapter("Chapter 1", "Ovo je sadržaj Chapter 1, druge knjige");
            //book2.AddChapter("Chapter 2", "Ovo je sadržaj Chapter 2, druge knjige");

            //book3.AddChapter("Chapter 1", "Ovo je sadržaj Chapter 1, treće knjige");
            //book3.AddChapter("Chapter 2", "Ovo je sadržaj Chapter 2, treće knjige");

            //listaKnjiga.Add(book1);
            //listaKnjiga.Add(book2);
            //listaKnjiga.Add(book3);

            //genre1.Books.Add(book1);
            //genre2.Books.Add(book2);
            //genre3.Books.Add(book3);

            //listaZanrova.Add(genre1);
            //listaZanrova.Add(genre2);
            //listaZanrova.Add(genre3);
        #endregion

            //listaKnjiga = (List<Book>)bookRepo.GetAll();
            //listaZanrova = (List<Genre>)genreRepo.GetAll();
        }
        

        private List<Book> SortBooks(IEnumerable<Book> listaKnjiga, string kriterijum)
        {
           
            List<Book> sortiranaLista;
            switch (kriterijum)
            {
                case "1":
                    sortiranaLista = (from b in listaKnjiga
                                      orderby b.Name ascending
                                      select b).ToList();

                    break;

                case "2":
                    sortiranaLista = (from b in listaKnjiga
                                      orderby b.Name descending
                                      select b).ToList();

                    break;

                case "3":
                    sortiranaLista = (from b in listaKnjiga
                                      orderby b.Price ascending
                                      select b).ToList();

                    break;

                case "4":
                    sortiranaLista = (from b in listaKnjiga
                                      orderby b.Price descending
                                      select b).ToList();
                    break;

                default:
                    sortiranaLista = (from b in listaKnjiga
                                      orderby b.Id ascending
                                      select b).ToList();
                    break;
            }

            return sortiranaLista;

        }

        [Route("dodaj-novu")]
        public ActionResult Index()
        {
            BookGenreViewModel vm = new BookGenreViewModel();

            vm.Genres = genreRepo.GetAll();
            return View(vm);
        }

        [Route("lista-knjiga")]
        public ActionResult List()
        {
            var books = bookRepo.GetAll().Where(b => b.isDeleted == false).ToList();
            return View(books);
            

            #region komentar za SelectList
            /*
             treba dodati SelectList u ViewBag/Session/gde god
             koji se koristi u Html.DropDownListFor da napravi
             select html element sa svim Genre-ovima


            ViewBag.Genres = new SelectList(storeDB.Genres.OrderBy(g => g.Name), 

             "GenreId", "Name", album.GenreId);
             */

            //ViewBag.Genres = new SelectList(listaZanrova.OrderBy(g => g.Name),

            // "Id", "Name", null);
            #endregion
        }



        //akcija za sortiranje
        [Route("lista-knjiga")]
        [HttpPost]
        public ActionResult List(string kriterijumSortiranja)
        {
            var books = bookRepo.GetAll().Where(b => b.isDeleted == false);
            var sortiranaLista = SortBooks(books, kriterijumSortiranja);
            if (sortiranaLista != null & sortiranaLista.Count > 0)
            {
                return View(sortiranaLista);
            }
            else
            {
                return View("List", null);
            }
        }

        [Route("obrisane")]
        public ActionResult Deleted()
        {
            var deletedBooks = bookRepo.GetAll().Where(b => b.isDeleted == true);
            return View(deletedBooks);
        }

        //akcija za sortiranje
        [Route("obrisane")]
        [HttpPost]
        public ActionResult Deleted(string kriterijumSortiranja)
        {
            var deletedBooks = bookRepo.GetAll().Where(b => b.isDeleted == true);
            var sortiranaLista = SortBooks(deletedBooks, kriterijumSortiranja);
            return View(sortiranaLista);
        }

        [HttpPost]

        public ActionResult AddBook(BookGenreViewModel vm)
        {
            Book book = vm.Book;
            Genre genre = genreRepo.GetById(vm.SelectedGenreId);
            book.Genre = genre;
            if (bookRepo.Create(book))
            {
                return RedirectToAction("List");
            }
            return View("Error");
          

            #region komenaterisan kod
            //if (ModelState.IsValid)
            //{

            // listaKnjiga.Add(book);
            // return RedirectToAction("List");
            //}

            //return View(book);

            //if (book != null)
            //{
            //    listaKnjiga.Add(book);
            //    return RedirectToAction("List");
            //}
            //else
            //{
            //    return View(book);
            //}
            #endregion
        }

        [HttpPost]
        public ActionResult DeleteBook(int Id)
        {
            bookRepo.Delete(Id);
          
            return RedirectToAction("List");

            // Book knjiga = null;
            //foreach (Book b in listaKnjiga)
            //{
            //    if (b.Id == Id)
            //    {
            //        b.isDeleted = true;
            //       // UKLANJANJE KNJIGE IZ Genre.Books kolekcije!
            //        b.Genre.Books.Remove(b);
            //        break;
            //    }
            //}
        }

        [Route("izmeni")]
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            BookGenreViewModel vm = new BookGenreViewModel();
            vm.Genres = genreRepo.GetAll();

            var book = bookRepo.GetAll().Where(b => b.Id == Id).SingleOrDefault();
            if (book != null)
            {
                vm.Book = book;
                return View(vm);
            }
            else
            {
                //ispraviti da obaveštava da nema knjiga sa tim Id
                return RedirectToAction("List");
            }

        }
        

        [Route("izmeni")]
        [HttpPost]
        //public ActionResult Edit(int Id, string Name, double Price, int GenreId)
        public ActionResult Edit(BookGenreViewModel vm)
        {

            Book book = bookRepo.GetAll().Where(b => b.Id == vm.Book.Id).SingleOrDefault();
            Genre genre = genreRepo.GetAll().Where(g => g.Id == vm.SelectedGenreId).SingleOrDefault();

            if (book != null && genre != null)
            {
                book.Name = vm.Book.Name;
                book.Price = vm.Book.Price;
                book.Genre = genre;

                bookRepo.Update(book);

                return RedirectToAction("List");
            }
            return RedirectToAction("List");
        }
    }
}

Domaci_MVC_1/Views/Bookstore/Deleted.cshtml
@using Domaci_MVC_1.Models;
@using Domaci_MVC_1.Controllers;

@model IEnumerable<Book>

@{
    ViewBag.Title = "Lista obrisanih knjiga";
}

<h2>Deleted books</h2>

@{
    if (Model != null)
    {
        <table id="filterForm_list">
            <tr>
                <td colspan="2">
                    <span><b>Sortiraj: </b></span>
                </td>
            </tr>
            <tr>
                <td>
                    @using (Html.BeginForm("Deleted", "Bookstore", FormMethod.Post))
                    {
                    @*<form method="post" action="/Bookstore/Deleted/">*@
                        <select name="kriterijumSortiranja">
                            <option value="1">po nazivu (A-Z)</option>
                            <option value="2">po nazivu (Z-A)</option>
                            <option value="3">po ceni (rastuće)</option>
                            <option value="4">po ceni (opadajuće)</option>
                        </select>
                        <input type="submit" value="sortiraj" />
                    }
                    @*</form>*@
                </td>
            </tr>
        </table>
        <br />
        <table class="table-striped table-bordered">
            <tr>
                @*<th>Id</th>*@
                <th>Name</th>
                <th>Price</th>
                <th>Genre</th>
            </tr>
            @foreach (Book b in Model)
            {
                if (b.isDeleted)
                {
                    <tr>
                        @*<td>@b.Id</td>*@
                        <td>@b.Name</td>
                        <td>@b.Price</td>
                        <td>@b.Genre.Name</td>
                    </tr>
                }

            }
        </table>
    }
    else
    {
        <h2 class="alert-warning">Nema knjiga za prikaz!</h2>
    }

}
        

<div>
    @Html.ActionLink("Add more books | ", "Index", "Bookstore")
    @Html.ActionLink("Show all books", "List", "Bookstore")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Domaci_MVC_1/Views/Bookstore/Edit.cshtml
@using Domaci_MVC_1.Models;
@using Domaci_MVC_1.ViewModels;
@using Domaci_MVC_1.Controllers;

@*@model Domaci_MVC_1.Models.Book*@
@model Domaci_MVC_1.ViewModels.BookGenreViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Bookstore", new { Id = Model.Book.Id }, FormMethod.Post))
{

    <div class="form-horizontal">
        <h4>Book: @Model.Book.Name</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Book.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Book.Name, "Name of the book", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.Name,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book.Price, "Price of the book", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Book.Genre, "Genre of the book", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

               
                <select name="SelectedGenreId">
                    @foreach (var item in Model.Genres)
                    {
                        if (item.Id == Model.Book.Genre.Id)
                        {
                            <option value="@item.Id" selected>@item.Name</option>
                            }
                            else
                            {
                                <option value="@item.Id">@item.Name</option>
                            }

                    }
                </select>
            </div>
            <div>
                @*@Html.Hidden("Id", Model.Genre.Id)*@
            </div>
        </div>

     

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save changes" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Domaci_MVC_1/Views/Bookstore/Index.cshtml
@using Domaci_MVC_1.Models;
@using Domaci_MVC_1.ViewModels;
@using Domaci_MVC_1.Controllers;

@*@model IEnumerable<Book>*@
@model Domaci_MVC_1.ViewModels.BookGenreViewModel

@{
    ViewBag.Title = "Dodavanje knjiga";
}

<h2>Bookstore - Home page</h2>
@Html.ValidationSummary()
<form action="/Bookstore/AddBook" method="post">
    <table class="table-striped table-bordered">
        <tr>
            <th colspan="2" style="text-align: center">
                Add new book
            </th>
        </tr>
        <tr>
            <td>Name of book</td>
            <td>
                <input type="text" name="Book.Name"/>
            </td>
        </tr>
        <tr>
            <td>Price of book</td>
            <td>
                <input type="text" name="Book.Price"/>
            </td>
        </tr>
        <tr>
            <td>Genre of book</td>
            <td>
                
             @* treba odraditi DropdownList
    @Html.DropDownList("Genre")*@
              
                <select name="SelectedGenreId">
                    @foreach (var b in Model.Genres)
                    {
                        if (b.isDeleted == false)
                        {
                            <option value="@b.Id">@b.Name</option>
                        }
                    }
                </select>
            </td>
        </tr>
        <tr style="text-align: right">
            <td colspan="2">
                <input type="submit" value="Add" />
            </td>
        </tr>
    </table>
</form>
<div style="display: inline-block;">
    @Html.ActionLink("Show all books | ", "List", "Bookstore")
</div>
<div style="display: inline-block;">
    @Html.ActionLink("Show deleted books", "Deleted", "Bookstore")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Domaci_MVC_1/Views/Bookstore/List.cshtml
@using Domaci_MVC_1.Models;
@using Domaci_MVC_1.Controllers;

@model IEnumerable<Book>

@{
    ViewBag.Title = "Lista svih knjiga";
}

<h2>All books:</h2>

@{ if (Model != null)
    {
        <table id="filterForm_list">
            <tr >
                <td colspan="2">
                    <span><b>Sortiraj: </b></span>
                </td>
            </tr>
            <tr>
                <td>
                    @using (Html.BeginForm("List", "Bookstore", FormMethod.Post))
                    { 
                    
                        <select name="kriterijumSortiranja">
                            <option value="1">po nazivu (A-Z)</option>
                            <option value="2">po nazivu (Z-A)</option>
                            <option value="3" selected>po ceni (rastuće)</option>
                            <option value="4">po ceni (opadajuće)</option>
                        </select>
                        <button type="submit"  value="sortiraj" class="glyphicon glyphicon-sort" title="sortiraj" />
                    }
                   
                </td>
            </tr>
        </table>
        <br />
        <table class="table-striped table-bordered" style="min-width: 400px">
            
            <tr>
                @*<th>Id</th>*@
                <th>@Html.DisplayNameFor(m => m.Name)</th>
                <th>@Html.DisplayNameFor(m => m.Price)</th>
                <th>@Html.DisplayNameFor(m => m.Genre)</th>
                <th colspan="2"></th>
            </tr>
            @foreach (Book b in Model)
                    {
                        if (!b.isDeleted)
                        {
                    <tr>
                        @*<td>@b.Id</td>
                        <td>@b.Name)</td>
                        <td>@b.Price</td>
                        <td>@b.Genre.Name</td>*@

                        <td>@Html.DisplayFor(modelitem => @b.Name)</td>
                        <td>@Html.DisplayFor(modelitem => @b.Price)</td>
                        <td>@Html.DisplayFor(modelitem => @b.Genre.Name)</td>
                        <td>
                            @using (Html.BeginForm("DeleteBook", "Bookstore", new { Id = @b.Id }, FormMethod.Post, null))
                            {
                                @*@Html.Hidden("Id", @b.Id)*@
                                <button type="submit" class="glyphicon glyphicon-remove btn btn-link" title="Delete book" />
                            }
                        </td>
                        <td>
                            @using (Html.BeginForm("Edit", "Bookstore", new { Id = @b.Id }, FormMethod.Get, null))
                            {
                                @*PITATI NA PREDAVANJU ZASTO NE SALJE ID AKO NEMA HIDDEN ELEMENTA ZA ID*@
                                @Html.Hidden("Id", @b.Id)
                                <button type="submit" class="glyphicon glyphicon-edit btn btn-link" title="Edit book" />
                            }
                        </td>
                    </tr>
                }

            }
        </table>
    }
    else
    {
        <h2 class="alert-warning">Nema knjiga za prikaz!</h2>
    }
}


<div>
   @Html.ActionLink("Add more books | ", "Index", "Bookstore")
    @Html.ActionLink("Deleted books", "Deleted", "Bookstore")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}