Domaci_MVC_1/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Domaci_MVC_1.Models
{
    public class Genre
    {
        private static int IdCounter = 1;
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public List<Book> Books { get; set; }
        public bool isDeleted { get; set; }

        public Genre()
        {
            //this.Id = IdCounter;
            //IdCounter++;
            this.Books = new List<Book>();
            this.Name = "";
            this.isDeleted = false;
        }
       
        public Genre(string name)
        {
            
                //this.Id = IdCounter;
                //IdCounter++;
            this.Books = new List<Book>();
                this.Name = name;
            this.isDeleted = false;

        }
        public Genre(string name, List<Book> books)
        {
            //this.Id = IdCounter;
            //IdCounter++;
            this.Books = books;
            this.Name = name;
            this.isDeleted = false;
        }
    }
}

Domaci_MVC_1/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domaci_MVC_1.Models;
using Domaci_MVC_1.ViewModels;
using Domaci_MVC_1.Repository;

namespace Domaci_MVC_1.Controllers
{
    [RoutePrefix("zanr")]
    public class GenreController : Controller
    {
        private IRepository<Genre> genreRepo = new GenreRepository();
        private static IRepository<Book> bookRepo = new BookRepository();

        [Route("")]
        public ActionResult Index()
        {
            var genres = genreRepo.GetAll();
            return View(genres);
        }

        [Route("detalji")]
        public ActionResult Details(int id)
        {
            Genre genre = genreRepo.GetById(id);
            var books = bookRepo.GetAll().Where(b => b.Genre.Id == id).ToList();
            if (genre != null)
            {
                if (books.Count > 0)
                {
                    genre.Books = books;
                }
                return View(genre);
            }
            else
            {
                return Content("nema bre");
            }
        }

        [Route("novi")]
        public ActionResult Create()
        {
            return View();
        }

        [Route("novi")]
        [HttpPost]
        public ActionResult Create(string Name)
        {

            Genre genre = new Genre(Name);
            if (genreRepo.Create(genre))
            {
                return RedirectToAction("Index");
            }
            return View(genre);
            
            //try
            //{
            //    Genre genre = new Genre(Name);
            //    if (!BookstoreController.listaZanrova.Contains(genre))
            //    {
            //        BookstoreController.listaZanrova.Add(genre);
                    
            //    }
            //    if (genreRepo.Create(genre))
            //    {
            //        return RedirectToAction("Index");
            //    }
            //    else
            //    {
            //        return View();

            //    }

            //    //return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        [Route("izmeni")]
        public ActionResult Edit(int id)
        {
            Genre genre = genreRepo.GetById(id);
            if (genre != null)
            {
                return View(genre);
            }
            else
            {
                return Content("nema bre");
            }
        }

        [Route("izmeni")]
        [HttpPost]
        public ActionResult Edit(int id, string Name)
        {


            //Genre genre = BookstoreController.listaZanrova.Where(g => g.Id == id).SingleOrDefault();
            Genre genre = genreRepo.GetById(id);
                if (genre != null)
                {
                    genre.Name = Name;
                genreRepo.Update(genre);

                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("nema bre");
                }
                
           
        }



        [Route("obrisi")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            /*
             Da li bi pri brisanju žanra trebalo setovati na null Genre
             property svih knjiga koje su bile tog žanra ?
             */

            //Genre genre = BookstoreController.listaZanrova.Where(g => g.Id == id).SingleOrDefault();
            Genre genre = genreRepo.GetById(id);
            if (genre != null)
            {
                genre.isDeleted = true;
                genreRepo.Delete(id);
                return RedirectToAction("Index");

            }
            else
            {
                return Content("nema bre");
            }
        }
    }
}

Domaci_MVC_1/Views/Genre/Create.cshtml
@model Domaci_MVC_1.Models.Genre

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Genre", FormMethod.Post))
{

    <div class="form-horizontal">
        <h4>Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Domaci_MVC_1/Views/Genre/Details.cshtml
@model Domaci_MVC_1.Models.Genre

@{
    ViewBag.Title = "Details";
}

<h2>Details for genre: @Model.Name</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<div>
    @if (Model.Books != null && Model.Books.Count > 0)
    {
        <p>List of books:</p>
        <ul>
            @foreach (var b in Model.Books)
            {
                <li>@b.Name</li>
            }
        </ul>
    }
    else
    {
     <h2>No books in genre "@Model.Name"</h2>
    }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Domaci_MVC_1/Views/Genre/Edit.cshtml
@model Domaci_MVC_1.Models.Genre

@{
    ViewBag.Title = "Edit";
}

<h2>Genre - Edit</h2>


@using (Html.BeginForm())
{  
    <div class="form-horizontal">
        <h4>Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Domaci_MVC_1/Views/Genre/Index.cshtml
@model IEnumerable<Domaci_MVC_1.Models.Genre>

@{
    ViewBag.Title = "Index";
}

<h2>Genre - List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-striped" style="width:auto; min-width: 300px">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if (!item.isDeleted)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |

                    @*@Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
                    @*<span>
                        @using (Html.BeginForm("Delete", "Genre", new { id = @item.Id }, FormMethod.Post, null))
                    {
                            <input type="hidden" name="Id"/>
                            <input type="submit" value="Delete" class="btn btn-link" />
                        }
                    </span>*@
                </td>
            </tr>
        }


    }
</table>